//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("aapkikra_DBModel", "FK_ArticleEntry_ArticleCategory", "ArticleCategory", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AapkiMagazine.DataEntity.Prod.ArticleCategory), "ArticleEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AapkiMagazine.DataEntity.Prod.ArticleEntry), true)]
[assembly: EdmRelationshipAttribute("aapkikra_DBModel", "FK_ArticleEntry_Articles", "Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AapkiMagazine.DataEntity.Prod.Article), "ArticleEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AapkiMagazine.DataEntity.Prod.ArticleEntry), true)]
[assembly: EdmRelationshipAttribute("aapkikra_DBModel", "FK_ArticleEntry_PortalUserProfiles", "PortalUserProfiles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AapkiMagazine.DataEntity.Prod.PortalUserProfile), "ArticleEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AapkiMagazine.DataEntity.Prod.ArticleEntry), true)]

#endregion

namespace AapkiMagazine.DataEntity.Prod
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class aapkikra_DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new aapkikra_DBEntities object using the connection string found in the 'aapkikra_DBEntities' section of the application configuration file.
        /// </summary>
        public aapkikra_DBEntities() : base("name=aapkikra_DBEntities", "aapkikra_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new aapkikra_DBEntities object.
        /// </summary>
        public aapkikra_DBEntities(string connectionString) : base(connectionString, "aapkikra_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new aapkikra_DBEntities object.
        /// </summary>
        public aapkikra_DBEntities(EntityConnection connection) : base(connection, "aapkikra_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ArticleCategory> ArticleCategories
        {
            get
            {
                if ((_ArticleCategories == null))
                {
                    _ArticleCategories = base.CreateObjectSet<ArticleCategory>("ArticleCategories");
                }
                return _ArticleCategories;
            }
        }
        private ObjectSet<ArticleCategory> _ArticleCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ArticleEntry> ArticleEntries
        {
            get
            {
                if ((_ArticleEntries == null))
                {
                    _ArticleEntries = base.CreateObjectSet<ArticleEntry>("ArticleEntries");
                }
                return _ArticleEntries;
            }
        }
        private ObjectSet<ArticleEntry> _ArticleEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article> Articles
        {
            get
            {
                if ((_Articles == null))
                {
                    _Articles = base.CreateObjectSet<Article>("Articles");
                }
                return _Articles;
            }
        }
        private ObjectSet<Article> _Articles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BreakingNew> BreakingNews
        {
            get
            {
                if ((_BreakingNews == null))
                {
                    _BreakingNews = base.CreateObjectSet<BreakingNew>("BreakingNews");
                }
                return _BreakingNews;
            }
        }
        private ObjectSet<BreakingNew> _BreakingNews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Picture> Pictures
        {
            get
            {
                if ((_Pictures == null))
                {
                    _Pictures = base.CreateObjectSet<Picture>("Pictures");
                }
                return _Pictures;
            }
        }
        private ObjectSet<Picture> _Pictures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PortalUserProfile> PortalUserProfiles
        {
            get
            {
                if ((_PortalUserProfiles == null))
                {
                    _PortalUserProfiles = base.CreateObjectSet<PortalUserProfile>("PortalUserProfiles");
                }
                return _PortalUserProfiles;
            }
        }
        private ObjectSet<PortalUserProfile> _PortalUserProfiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Video> Videos
        {
            get
            {
                if ((_Videos == null))
                {
                    _Videos = base.CreateObjectSet<Video>("Videos");
                }
                return _Videos;
            }
        }
        private ObjectSet<Video> _Videos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ArticleCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticleCategories(ArticleCategory articleCategory)
        {
            base.AddObject("ArticleCategories", articleCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ArticleEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticleEntries(ArticleEntry articleEntry)
        {
            base.AddObject("ArticleEntries", articleEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticles(Article article)
        {
            base.AddObject("Articles", article);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BreakingNews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBreakingNews(BreakingNew breakingNew)
        {
            base.AddObject("BreakingNews", breakingNew);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pictures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPictures(Picture picture)
        {
            base.AddObject("Pictures", picture);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PortalUserProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPortalUserProfiles(PortalUserProfile portalUserProfile)
        {
            base.AddObject("PortalUserProfiles", portalUserProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Videos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVideos(Video video)
        {
            base.AddObject("Videos", video);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<HomePageDataByCategory> GetHomePageDataByCategory()
        {
            return base.ExecuteFunction<HomePageDataByCategory>("GetHomePageDataByCategory");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="Article")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        public static Article CreateArticle(global::System.Int32 id, global::System.DateTime created_date)
        {
            Article article = new Article();
            article.id = id;
            article.created_date = created_date;
            return article;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                Onmodified_dateChanging(value);
                ReportPropertyChanging("modified_date");
                _modified_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified_date");
                Onmodified_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified_date;
        partial void Onmodified_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodified_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aapkikra_DBModel", "FK_ArticleEntry_Articles", "ArticleEntry")]
        public ArticleEntry ArticleEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_Articles", "ArticleEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_Articles", "ArticleEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ArticleEntry> ArticleEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_Articles", "ArticleEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_Articles", "ArticleEntry", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="ArticleCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ArticleCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ArticleCategory object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static ArticleCategory CreateArticleCategory(global::System.Int32 id)
        {
            ArticleCategory articleCategory = new ArticleCategory();
            articleCategory.id = id;
            return articleCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name_english
        {
            get
            {
                return _name_english;
            }
            set
            {
                Onname_englishChanging(value);
                ReportPropertyChanging("name_english");
                _name_english = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name_english");
                Onname_englishChanged();
            }
        }
        private global::System.String _name_english;
        partial void Onname_englishChanging(global::System.String value);
        partial void Onname_englishChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aapkikra_DBModel", "FK_ArticleEntry_ArticleCategory", "ArticleEntry")]
        public EntityCollection<ArticleEntry> ArticleEntries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_ArticleCategory", "ArticleEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_ArticleCategory", "ArticleEntry", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="ArticleEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ArticleEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ArticleEntry object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static ArticleEntry CreateArticleEntry(global::System.Int32 id, global::System.Guid user_id)
        {
            ArticleEntry articleEntry = new ArticleEntry();
            articleEntry.id = id;
            articleEntry.user_id = user_id;
            return articleEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> category_id
        {
            get
            {
                return _category_id;
            }
            set
            {
                Oncategory_idChanging(value);
                ReportPropertyChanging("category_id");
                _category_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("category_id");
                Oncategory_idChanged();
            }
        }
        private Nullable<global::System.Int32> _category_id;
        partial void Oncategory_idChanging(Nullable<global::System.Int32> value);
        partial void Oncategory_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title_url
        {
            get
            {
                return _title_url;
            }
            set
            {
                Ontitle_urlChanging(value);
                ReportPropertyChanging("title_url");
                _title_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title_url");
                Ontitle_urlChanged();
            }
        }
        private global::System.String _title_url;
        partial void Ontitle_urlChanging(global::System.String value);
        partial void Ontitle_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content_full
        {
            get
            {
                return _content_full;
            }
            set
            {
                Oncontent_fullChanging(value);
                ReportPropertyChanging("content_full");
                _content_full = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content_full");
                Oncontent_fullChanged();
            }
        }
        private global::System.String _content_full;
        partial void Oncontent_fullChanging(global::System.String value);
        partial void Oncontent_fullChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Byte> _active;
        partial void OnactiveChanging(Nullable<global::System.Byte> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picture_url
        {
            get
            {
                return _picture_url;
            }
            set
            {
                Onpicture_urlChanging(value);
                ReportPropertyChanging("picture_url");
                _picture_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picture_url");
                Onpicture_urlChanged();
            }
        }
        private global::System.String _picture_url;
        partial void Onpicture_urlChanging(global::System.String value);
        partial void Onpicture_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String video_url
        {
            get
            {
                return _video_url;
            }
            set
            {
                Onvideo_urlChanging(value);
                ReportPropertyChanging("video_url");
                _video_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("video_url");
                Onvideo_urlChanged();
            }
        }
        private global::System.String _video_url;
        partial void Onvideo_urlChanging(global::System.String value);
        partial void Onvideo_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tags
        {
            get
            {
                return _tags;
            }
            set
            {
                OntagsChanging(value);
                ReportPropertyChanging("tags");
                _tags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tags");
                OntagsChanged();
            }
        }
        private global::System.String _tags;
        partial void OntagsChanging(global::System.String value);
        partial void OntagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String company
        {
            get
            {
                return _company;
            }
            set
            {
                OncompanyChanging(value);
                ReportPropertyChanging("company");
                _company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("company");
                OncompanyChanged();
            }
        }
        private global::System.String _company;
        partial void OncompanyChanging(global::System.String value);
        partial void OncompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_emailid
        {
            get
            {
                return _user_emailid;
            }
            set
            {
                Onuser_emailidChanging(value);
                ReportPropertyChanging("user_emailid");
                _user_emailid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_emailid");
                Onuser_emailidChanged();
            }
        }
        private global::System.String _user_emailid;
        partial void Onuser_emailidChanging(global::System.String value);
        partial void Onuser_emailidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> published
        {
            get
            {
                return _published;
            }
            set
            {
                OnpublishedChanging(value);
                ReportPropertyChanging("published");
                _published = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("published");
                OnpublishedChanged();
            }
        }
        private Nullable<global::System.Byte> _published;
        partial void OnpublishedChanging(Nullable<global::System.Byte> value);
        partial void OnpublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> isbreakingnews
        {
            get
            {
                return _isbreakingnews;
            }
            set
            {
                OnisbreakingnewsChanging(value);
                ReportPropertyChanging("isbreakingnews");
                _isbreakingnews = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isbreakingnews");
                OnisbreakingnewsChanged();
            }
        }
        private Nullable<global::System.Byte> _isbreakingnews;
        partial void OnisbreakingnewsChanging(Nullable<global::System.Byte> value);
        partial void OnisbreakingnewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> isfrontslider
        {
            get
            {
                return _isfrontslider;
            }
            set
            {
                OnisfrontsliderChanging(value);
                ReportPropertyChanging("isfrontslider");
                _isfrontslider = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isfrontslider");
                OnisfrontsliderChanged();
            }
        }
        private Nullable<global::System.Byte> _isfrontslider;
        partial void OnisfrontsliderChanging(Nullable<global::System.Byte> value);
        partial void OnisfrontsliderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Guid _user_id;
        partial void Onuser_idChanging(global::System.Guid value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content_summary
        {
            get
            {
                return _content_summary;
            }
            set
            {
                Oncontent_summaryChanging(value);
                ReportPropertyChanging("content_summary");
                _content_summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content_summary");
                Oncontent_summaryChanged();
            }
        }
        private global::System.String _content_summary;
        partial void Oncontent_summaryChanging(global::System.String value);
        partial void Oncontent_summaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title_english
        {
            get
            {
                return _title_english;
            }
            set
            {
                Ontitle_englishChanging(value);
                ReportPropertyChanging("title_english");
                _title_english = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title_english");
                Ontitle_englishChanged();
            }
        }
        private global::System.String _title_english;
        partial void Ontitle_englishChanging(global::System.String value);
        partial void Ontitle_englishChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title_seo
        {
            get
            {
                return _title_seo;
            }
            set
            {
                Ontitle_seoChanging(value);
                ReportPropertyChanging("title_seo");
                _title_seo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title_seo");
                Ontitle_seoChanged();
            }
        }
        private global::System.String _title_seo;
        partial void Ontitle_seoChanging(global::System.String value);
        partial void Ontitle_seoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aapkikra_DBModel", "FK_ArticleEntry_ArticleCategory", "ArticleCategory")]
        public ArticleCategory ArticleCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleCategory>("aapkikra_DBModel.FK_ArticleEntry_ArticleCategory", "ArticleCategory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleCategory>("aapkikra_DBModel.FK_ArticleEntry_ArticleCategory", "ArticleCategory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ArticleCategory> ArticleCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ArticleCategory>("aapkikra_DBModel.FK_ArticleEntry_ArticleCategory", "ArticleCategory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ArticleCategory>("aapkikra_DBModel.FK_ArticleEntry_ArticleCategory", "ArticleCategory", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aapkikra_DBModel", "FK_ArticleEntry_Articles", "Articles")]
        public Article Article
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("aapkikra_DBModel.FK_ArticleEntry_Articles", "Articles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("aapkikra_DBModel.FK_ArticleEntry_Articles", "Articles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Article> ArticleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Article>("aapkikra_DBModel.FK_ArticleEntry_Articles", "Articles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Article>("aapkikra_DBModel.FK_ArticleEntry_Articles", "Articles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aapkikra_DBModel", "FK_ArticleEntry_PortalUserProfiles", "PortalUserProfiles")]
        public PortalUserProfile PortalUserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortalUserProfile>("aapkikra_DBModel.FK_ArticleEntry_PortalUserProfiles", "PortalUserProfiles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortalUserProfile>("aapkikra_DBModel.FK_ArticleEntry_PortalUserProfiles", "PortalUserProfiles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PortalUserProfile> PortalUserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PortalUserProfile>("aapkikra_DBModel.FK_ArticleEntry_PortalUserProfiles", "PortalUserProfiles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PortalUserProfile>("aapkikra_DBModel.FK_ArticleEntry_PortalUserProfiles", "PortalUserProfiles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="BreakingNew")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BreakingNew : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BreakingNew object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static BreakingNew CreateBreakingNew(global::System.Int32 id)
        {
            BreakingNew breakingNew = new BreakingNew();
            breakingNew.id = id;
            return breakingNew;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> article_id
        {
            get
            {
                return _article_id;
            }
            set
            {
                Onarticle_idChanging(value);
                ReportPropertyChanging("article_id");
                _article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("article_id");
                Onarticle_idChanged();
            }
        }
        private Nullable<global::System.Int32> _article_id;
        partial void Onarticle_idChanging(Nullable<global::System.Int32> value);
        partial void Onarticle_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="Picture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Picture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Picture object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Picture CreatePicture(global::System.Int32 id)
        {
            Picture picture = new Picture();
            picture.id = id;
            return picture;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picture_url
        {
            get
            {
                return _picture_url;
            }
            set
            {
                Onpicture_urlChanging(value);
                ReportPropertyChanging("picture_url");
                _picture_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picture_url");
                Onpicture_urlChanged();
            }
        }
        private global::System.String _picture_url;
        partial void Onpicture_urlChanging(global::System.String value);
        partial void Onpicture_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> article_id
        {
            get
            {
                return _article_id;
            }
            set
            {
                Onarticle_idChanging(value);
                ReportPropertyChanging("article_id");
                _article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("article_id");
                Onarticle_idChanged();
            }
        }
        private Nullable<global::System.Int32> _article_id;
        partial void Onarticle_idChanging(Nullable<global::System.Int32> value);
        partial void Onarticle_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="PortalUserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PortalUserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PortalUserProfile object.
        /// </summary>
        /// <param name="user_Id">Initial value of the User_Id property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        /// <param name="user_email">Initial value of the user_email property.</param>
        public static PortalUserProfile CreatePortalUserProfile(global::System.Guid user_Id, global::System.String first_name, global::System.String last_name, global::System.String password, global::System.String role, global::System.String user_email)
        {
            PortalUserProfile portalUserProfile = new PortalUserProfile();
            portalUserProfile.User_Id = user_Id;
            portalUserProfile.first_name = first_name;
            portalUserProfile.last_name = last_name;
            portalUserProfile.Password = password;
            portalUserProfile.Role = role;
            portalUserProfile.user_email = user_email;
            return portalUserProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid User_Id
        {
            get
            {
                return _User_Id;
            }
            set
            {
                if (_User_Id != value)
                {
                    OnUser_IdChanging(value);
                    ReportPropertyChanging("User_Id");
                    _User_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("User_Id");
                    OnUser_IdChanged();
                }
            }
        }
        private global::System.Guid _User_Id;
        partial void OnUser_IdChanging(global::System.Guid value);
        partial void OnUser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_email
        {
            get
            {
                return _user_email;
            }
            set
            {
                Onuser_emailChanging(value);
                ReportPropertyChanging("user_email");
                _user_email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_email");
                Onuser_emailChanged();
            }
        }
        private global::System.String _user_email;
        partial void Onuser_emailChanging(global::System.String value);
        partial void Onuser_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String salt
        {
            get
            {
                return _salt;
            }
            set
            {
                OnsaltChanging(value);
                ReportPropertyChanging("salt");
                _salt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("salt");
                OnsaltChanged();
            }
        }
        private global::System.String _salt;
        partial void OnsaltChanging(global::System.String value);
        partial void OnsaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> pwdchangedate
        {
            get
            {
                return _pwdchangedate;
            }
            set
            {
                OnpwdchangedateChanging(value);
                ReportPropertyChanging("pwdchangedate");
                _pwdchangedate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pwdchangedate");
                OnpwdchangedateChanged();
            }
        }
        private Nullable<global::System.DateTime> _pwdchangedate;
        partial void OnpwdchangedateChanging(Nullable<global::System.DateTime> value);
        partial void OnpwdchangedateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("aapkikra_DBModel", "FK_ArticleEntry_PortalUserProfiles", "ArticleEntry")]
        public EntityCollection<ArticleEntry> ArticleEntries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_PortalUserProfiles", "ArticleEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ArticleEntry>("aapkikra_DBModel.FK_ArticleEntry_PortalUserProfiles", "ArticleEntry", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Tag CreateTag(global::System.Int32 id)
        {
            Tag tag = new Tag();
            tag.id = id;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String articles
        {
            get
            {
                return _articles;
            }
            set
            {
                OnarticlesChanging(value);
                ReportPropertyChanging("articles");
                _articles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("articles");
                OnarticlesChanged();
            }
        }
        private global::System.String _articles;
        partial void OnarticlesChanging(global::System.String value);
        partial void OnarticlesChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="aapkikra_DBModel", Name="Video")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Video : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Video object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Video CreateVideo(global::System.Int32 id)
        {
            Video video = new Video();
            video.id = id;
            return video;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String video_url
        {
            get
            {
                return _video_url;
            }
            set
            {
                Onvideo_urlChanging(value);
                ReportPropertyChanging("video_url");
                _video_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("video_url");
                Onvideo_urlChanged();
            }
        }
        private global::System.String _video_url;
        partial void Onvideo_urlChanging(global::System.String value);
        partial void Onvideo_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> article_id
        {
            get
            {
                return _article_id;
            }
            set
            {
                Onarticle_idChanging(value);
                ReportPropertyChanging("article_id");
                _article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("article_id");
                Onarticle_idChanged();
            }
        }
        private Nullable<global::System.Int32> _article_id;
        partial void Onarticle_idChanging(Nullable<global::System.Int32> value);
        partial void Onarticle_idChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="aapkikra_DBModel", Name="HomePageDataByCategory")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class HomePageDataByCategory : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HomePageDataByCategory object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="created_date">Initial value of the created_date property.</param>
        public static HomePageDataByCategory CreateHomePageDataByCategory(global::System.Int32 id, global::System.DateTime created_date)
        {
            HomePageDataByCategory homePageDataByCategory = new HomePageDataByCategory();
            homePageDataByCategory.id = id;
            homePageDataByCategory.created_date = created_date;
            return homePageDataByCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                Onmodified_dateChanging(value);
                ReportPropertyChanging("modified_date");
                _modified_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified_date");
                Onmodified_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified_date;
        partial void Onmodified_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodified_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime created_date
        {
            get
            {
                return _created_date;
            }
            set
            {
                Oncreated_dateChanging(value);
                ReportPropertyChanging("created_date");
                _created_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created_date");
                Oncreated_dateChanged();
            }
        }
        private global::System.DateTime _created_date;
        partial void Oncreated_dateChanging(global::System.DateTime value);
        partial void Oncreated_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> category_id
        {
            get
            {
                return _category_id;
            }
            set
            {
                Oncategory_idChanging(value);
                ReportPropertyChanging("category_id");
                _category_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("category_id");
                Oncategory_idChanged();
            }
        }
        private Nullable<global::System.Int32> _category_id;
        partial void Oncategory_idChanging(Nullable<global::System.Int32> value);
        partial void Oncategory_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Byte> _active;
        partial void OnactiveChanging(Nullable<global::System.Byte> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picture_url
        {
            get
            {
                return _picture_url;
            }
            set
            {
                Onpicture_urlChanging(value);
                ReportPropertyChanging("picture_url");
                _picture_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picture_url");
                Onpicture_urlChanged();
            }
        }
        private global::System.String _picture_url;
        partial void Onpicture_urlChanging(global::System.String value);
        partial void Onpicture_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String video_url
        {
            get
            {
                return _video_url;
            }
            set
            {
                Onvideo_urlChanging(value);
                ReportPropertyChanging("video_url");
                _video_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("video_url");
                Onvideo_urlChanged();
            }
        }
        private global::System.String _video_url;
        partial void Onvideo_urlChanging(global::System.String value);
        partial void Onvideo_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tags
        {
            get
            {
                return _tags;
            }
            set
            {
                OntagsChanging(value);
                ReportPropertyChanging("tags");
                _tags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tags");
                OntagsChanged();
            }
        }
        private global::System.String _tags;
        partial void OntagsChanging(global::System.String value);
        partial void OntagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String company
        {
            get
            {
                return _company;
            }
            set
            {
                OncompanyChanging(value);
                ReportPropertyChanging("company");
                _company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("company");
                OncompanyChanged();
            }
        }
        private global::System.String _company;
        partial void OncompanyChanging(global::System.String value);
        partial void OncompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> published
        {
            get
            {
                return _published;
            }
            set
            {
                OnpublishedChanging(value);
                ReportPropertyChanging("published");
                _published = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("published");
                OnpublishedChanged();
            }
        }
        private Nullable<global::System.Byte> _published;
        partial void OnpublishedChanging(Nullable<global::System.Byte> value);
        partial void OnpublishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> isbreakingnews
        {
            get
            {
                return _isbreakingnews;
            }
            set
            {
                OnisbreakingnewsChanging(value);
                ReportPropertyChanging("isbreakingnews");
                _isbreakingnews = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isbreakingnews");
                OnisbreakingnewsChanged();
            }
        }
        private Nullable<global::System.Byte> _isbreakingnews;
        partial void OnisbreakingnewsChanging(Nullable<global::System.Byte> value);
        partial void OnisbreakingnewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> isfrontslider
        {
            get
            {
                return _isfrontslider;
            }
            set
            {
                OnisfrontsliderChanging(value);
                ReportPropertyChanging("isfrontslider");
                _isfrontslider = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isfrontslider");
                OnisfrontsliderChanged();
            }
        }
        private Nullable<global::System.Byte> _isfrontslider;
        partial void OnisfrontsliderChanging(Nullable<global::System.Byte> value);
        partial void OnisfrontsliderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content_summary
        {
            get
            {
                return _content_summary;
            }
            set
            {
                Oncontent_summaryChanging(value);
                ReportPropertyChanging("content_summary");
                _content_summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content_summary");
                Oncontent_summaryChanged();
            }
        }
        private global::System.String _content_summary;
        partial void Oncontent_summaryChanging(global::System.String value);
        partial void Oncontent_summaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title_seo
        {
            get
            {
                return _title_seo;
            }
            set
            {
                Ontitle_seoChanging(value);
                ReportPropertyChanging("title_seo");
                _title_seo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title_seo");
                Ontitle_seoChanged();
            }
        }
        private global::System.String _title_seo;
        partial void Ontitle_seoChanging(global::System.String value);
        partial void Ontitle_seoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RowNbr
        {
            get
            {
                return _RowNbr;
            }
            set
            {
                OnRowNbrChanging(value);
                ReportPropertyChanging("RowNbr");
                _RowNbr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RowNbr");
                OnRowNbrChanged();
            }
        }
        private Nullable<global::System.Int64> _RowNbr;
        partial void OnRowNbrChanging(Nullable<global::System.Int64> value);
        partial void OnRowNbrChanged();

        #endregion
    }

    #endregion
    
}
